name: Cypress Tests

on:
  push:
    branches:
      - main  # Modify this to match your main branch name

jobs:
  cypress:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Modify this to match your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run test:e2e -- --spec "cypress/e2e/spec-copy-1.cy.js"
